version: '3.7'

services:

  country:
    image: ghcr.io/xai-demonstrator/guess-the-country-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ROOT_PATH=/api/country
      - SERVICE_NAME=country-service
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger
      - GOOGLE_MAPS_API_TOKEN=${STREETVIEW_API_KEY}

  jaeger:
    image: jaegertracing/all-in-one
    expose:
      - 6831
    ports:
      - 16686:16686
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
