version: '3.8'

services:
  nginx:
      build:
        context: .
        dockerfile: ./nginx-frontend/Dockerfile
      depends_on:
        - education
        - study
      expose:
        - 80
      environment:
        - VIRTUAL_HOST=gtc.xaidemo.de
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=gtc.xaidemo.de
        - LETSENCRYPT_EMAIL=xai.demonstrator@gmail.com
      restart: always

  study:
    build:
        context: .
        dockerfile: ./study/Dockerfile
    depends_on:
      - collector
    expose:
      - 8000
    environment:
      - ROOT_PATH=/api/study
      - SERVICE_NAME=study-backend-service
      - COLLECTOR_URL=http://collector:8000
      - EXPERIMENT=1 
    volumes:
        - ./../../../images:/images/

  education:      
    image: ghcr.io/xai-demonstrator/digital-education-service:latest
    depends_on:
      - jaeger
    expose:
      - 8000
    environment:
      - ROOT_PATH=/api/education
      - SERVICE_NAME=education-service
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger
        

  jaeger:
    image: jaegertracing/all-in-one
    expose:
      - 6831
    ports:
      - 16686:16686
    restart: always


  collector:
    image: ghcr.io/xai-demonstrator/data-collector:latest
    depends_on:
      - couchdb
    expose:
      - "8000"
    ports:
      - "8001:8000"
    environment:
      - SERVICE_NAME=data-collector
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger

  proxy:
    image: ghcr.io/xai-demonstrator/experiment-proxy:latest
    depends_on:
      - collector
      - education
      - study
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://education:8000
      - BACKEND_SERVICE=test-case
      - COLLECTOR_URL=http://collector:8000
      - SERVICE_NAME=experiment-proxy
      - TRACING_EXPORTER=jaeger
      - JAEGER_AGENT_HOST_NAME=jaeger


networks:
  default:
    external:
      name: nginx-proxy
