version: '3.8'

services:

  backend:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./vue-webapp
    volumes:
      - './vue-webapp:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080