version: '3.7'

services:
  landing:
    image: ghcr.io/xai-demonstrator/landing-page-service:latest
    depends_on:
      - inspection
      - sentiment
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=test.xaidemo.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test.xaidemo.de
      - LETSENCRYPT_EMAIL=xai.demonstrator@gmail.com
    restart: always

  sentiment:
    image: ghcr.io/xai-demonstrator/review-sentiment-service:latest

  inspection:
    image: ghcr.io/xai-demonstrator/visual-inspection-service:latest

networks:
  default:
    external:
      name: nginx-proxy
