name: Documentation

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Deploy MkDocs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
