name: Guess the Country

on:
  push:
    paths:
      - 'guess-the-country/**'
      - '!guess-the-country/tests/**'
      - '!guess-the-country/**.md'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./guess-the-country/country-backend/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          set -e
          cd ./guess-the-country/country-backend
          echo $PWD
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          set -e
          cd ./guess-the-country/country-backend
          echo $PWD
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./guess-the-country/country-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          set -e
          cd ./guess-the-country/country-frontend
          echo $PWD
          npm install

  build:
    runs-on: ubuntu-latest
    needs:
      - test-backend
      - test-frontend
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.8

    - uses: actions/cache@v2.1.6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('./guess-the-country/country-backend/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        set -e
        cd ./guess-the-country/country-backend
        echo $PWD
        python -m pip install --upgrade pip
        pip install -r requirements.txt
