name: Monitor Deployment(s)
on:
  schedule:
    - cron: "5 * * * *"

jobs:
  test:
    name: Check Test Deployment
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v1.4
        with:
          url: https://test.xaidemo.de
          max-attempts: 3
          retry-delay: 30s
      - name: Notify Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: xai-tech
          SLACK_MESSAGE: 'Cannot reach test deployment at https://test.xaidemo.de :disappointed:'
          SLACK_TITLE: Test Deployment Is Down
          SLACK_USERNAME: Deployment Monitor
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
