name: Prod Deployment

on:
  push:
    branches: 
      prod_project

jobs:
  deploy-backends:
    strategy:
      matrix:
        include:
          - service: review-sentiment
            prefix: sentiment
            memory: 4Gi
          - service: visual-inspection
            prefix: inspection
            memory: 1Gi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_PROD_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker
        run: gcloud auth configure-docker

      - name: Pull, Tag, and Push Container
        run: |-
          echo check check
          docker pull ghcr.io/xai-demonstrator/${{ matrix.service }}-service:latest
          docker tag ghcr.io/xai-demonstrator/${{ matrix.service }}-service gcr.io/${{ secrets.GCP_PROD_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROD_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |-
            gcloud run deploy ${{ matrix.service }} \
              --region ${{ secrets.GCP_PROD_REGION }} \
              --image gcr.io/${{ secrets.GCP_PROD_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }} \
              --platform managed \
              --port 8000 \
              --memory "${{ matrix.memory }}" \
              --update-env-vars "PATH_PREFIX=/api/${{ matrix.prefix }}" \
              --update-env-vars "TRACING_EXPORTER=gcp"
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
