name: Prod Landing Page

on:
  push:
    branches:
      - master
    paths:
      - 'landing-page/frontend/**'
      
env:
  FRONTEND_PATH: ./landing-page/frontend/
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
      
      - name: Set Up Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./review-sentiment/sentiment-frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      - name: Build Frontend
        run: | 
            cd ${{ env.FRONTEND_PATH }}
            npm install
            npm run build -- --mode prod-deployment
            mv dist landing_page
            
      - name: Pushing Files to Cloud Storage
        id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.2.0
        with:
          credentials: ${{ secrets.GCP_TEST_SA_KEY }}
          path: ${{ env.FRONTEND_PATH }}/landing_page
          destination: demonstrator-static/
