name: Prod Deployment

on:
  workflow_dispatch

jobs:
  build-frontends:
    strategy:
      matrix:
        include:
          - service: sentiment
            repo_path: ./review-sentiment/sentiment-frontend/
          - service: inspection
            repo_path: ./visual-inspection/inspection-frontend/
          - service: landing-page
            repo_path: ./landing-page/frontend/

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('${{ matrix.repo_path }}') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Frontend
        run: |
          set -e
          cd ${{ matrix.repo_path }}
          npm install
          npm run build -- --mode prod-deployment
          mv dist ${{ matrix.service }}

      - name: Save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.service }}
          path: ${{ matrix.repo_path }}/${{ matrix.service }}
          retention-days: 3

  deploy-frontends:
    needs: build-frontends
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download all frontends
        uses: actions/download-artifact@v2
        with:
          path: ./deployment/prod-deployment/frontends/public

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_TEST_SA_KEY }}
          PROJECT_PATH: ./deployment/prod-deployment/frontends


  deploy-backends:
    strategy:
      matrix:
        include:
          - service: review-sentiment
            memory: 4Gi
          - service: visual-inspection
            memory: 1Gi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_TEST_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_TEST_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker pull ghcr.io/xai-demonstrator/${{ matrix.service }}-service:latest
          docker tag ghcr.io/xai-demonstrator/${{ matrix.service }}-service gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
            gcloud run deploy ${{ matrix.service }} \
              --region ${{ secrets.GCP_TEST_REGION }} \
              --image gcr.io/${{ secrets.GCP_TEST_PROJECT_ID }}/${{ matrix.service }}:${{ github.sha }} \
              --platform managed \
              --port 8000 \
              --memory "${{ matrix.memory }}"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}


  notify:
    needs:
      - deploy-frontends
      - deploy-backends
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: xai-tech
          SLACK_MESSAGE: 'Successfully deployed a new release to https://www.xaidemo.de :rocket:'
          SLACK_TITLE: New Prod Deployment
          SLACK_USERNAME: Deployment Monitor
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
