name: Prod Deployment sentiment-frontend

on:
  push:
    branches:
      - master
    paths:
      - 'review-sentiment/sentiment-frontend/**'
      
env:
  FRONTEND_PATH: ./review-sentiment/sentiment-frontend/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
      
      - name: Set Up Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'
        
      - name: Build Frontend
        run: | 
            cd ${{ env.FRONTEND_PATH }}
            npm install
            npm run build -- --mode prod-deployment
            mv dist sentiment

      - name: Pushing Files to Cloud Storage
        id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0.2.0
        with:
          credentials: ${{ secrets.GCP_TEST_SA_KEY }}
          path: ${{ env.FRONTEND_PATH }}/dist/.
          destination: sentiment-frontend/
      
