name: Test Deployment

on:
  workflow_run:
    workflows:
      - "Landing Page"
      - "Review Sentiment"
      - "Visual Inspection"
    branches:
      - master
    types:
      - completed
  push:
    branches:
      - master
    paths:
      - 'deployment/test-deployment/**'
      - '!deployment/test-deployment/**.md'

jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
       - name: Copy docker-compose.yml to test server
         uses: appleboy/scp-action@v0.1.1
         with:
           host: ${{ secrets.TEST_HOST }}
           username: ${{ secrets.TEST_USER }}
           key: ${{ secrets.TEST_KEY }}
           source: "deployment/test-deployment/docker-compose.yml"
           target: "test-deployment"
           rm: true
       - name: SSH Remote Commands
         uses: appleboy/ssh-action@v0.1.4
         with:
           host: ${{ secrets.TEST_HOST }}
           username: ${{ secrets.TEST_USER }}
           key: ${{ secrets.TEST_KEY }}
           script: |
             set -e
             cd test-deployment/deployment/test-deployment/
             sudo docker-compose down
             sudo docker-compose pull
             sudo docker-compose up -d
       - name: Slack Notification
         uses: rtCamp/action-slack-notify@master
         env:
            SLACK_CHANNEL: xai-tech
            SLACK_MESSAGE: 'Successfully deployed a new version to https://test.xaidemo.de :rocket:'
            SLACK_TITLE: New Test Deployment
            SLACK_USERNAME: Deployment Monitor
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            MSG_MINIMAL: true
