name: Visual Inspection

on:
  push:
    paths:
      - 'visual-inspection/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12
    - name: Build frontend
      run: |
        set -e
        cd ./visual-inspection/inspection-frontend
        echo $PWD
        npm install
        npm run build
