name: Vue Components

on:
  push:
    paths:
      - 'common/vue-components/**'
      - '!common/vue-components/**.md'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build xaidemo-ui library
        run: |
          set -e
          cd ./common/vue-components/xaidemo-ui
          npm install
          npm run build-lib
      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./common/vue-components/xaidemo-ui/package.json
          access: public
          check-version: true
          dry-run: github.ref != 'refs/heads/master'
